spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Tharunpranav@2k
    url: jdbc:mysql://localhost:3306/flightdatabase
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL57Dialect
